menu:
  Home: /
  Archives: /archives
  RSS: /atom.xml

widgets:
- search
- tagcloud
- recent_posts

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true

fancybox: true

google_analytics:
rss: /atom.xml

comment_provider: facebook
# Facebook comment
facebook:
  appid: 566574640079320
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light